<?php
/**
 * @file
 * fishers_wordpress_migration.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function fishers_wordpress_migration_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-media_gallery-field_nextgen_gid'
  $field_instances['node-media_gallery-field_nextgen_gid'] = array(
    'bundle' => 'media_gallery',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'This is the Nextgen gallery id from Wordpress.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 13,
      ),
      'full' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'media_gallery_block' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_nextgen_gid',
    'label' => 'Nextgen_gid',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 43,
    ),
  );

  // Exported field_instance: 'node-media_gallery-field_nextgen_path'
  $field_instances['node-media_gallery-field_nextgen_path'] = array(
    'bundle' => 'media_gallery',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The path that the gallery used to store its images.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 14,
      ),
      'full' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'media_gallery_block' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_nextgen_path',
    'label' => 'Nextgen path',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 44,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Nextgen path');
  t('Nextgen_gid');
  t('The path that the gallery used to store its images.');
  t('This is the Nextgen gallery id from Wordpress.');

  return $field_instances;
}
